### ISSUE TITLE
Fix flaky Test IssuesManagerTest.testRemoveIssues

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#284]
From https://ci.eclipse.org/udig/job/uDig-master-CI 

Stacktrace:
```

java.lang.AssertionError: expected:<10> but was:<11>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.locationtech.udig.issues.test.IssuesManagerTest.testRemoveIssues(IssuesManagerTest.java:78)
```

**Comment by fgdrf** [comment]
Waiting for feedback or master-CI job while build for pull request #291 was fine
