### ISSUE TITLE
StyleFactory is not an ImageIO SPI class

### ISSUE THREAD

**Issue by jconley** [locationtech/udig-platform#312]
2.0.0 fails on startup with "An error has occured" popup directing you to a logfile (below)

MacOS Mojave 10.14
```
$ java -version
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

```
$ cat 1539004925670.log
!SESSION 2018-10-08 08:22:05.475 -----------------------------------------------
eclipse.buildId=unknown
java.version=11
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/user/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/user/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2018-10-08 08:22:07.622
!MESSAGE Application error
!STACK 1
java.lang.ExceptionInInitializerError
        at org.locationtech.udig.libs.internal.Activator.doEpsg(Activator.java:274)
        at org.locationtech.udig.libs.internal.Activator.epsgDatabaseFile(Activator.java:259)
        at org.locationtech.udig.internal.ui.UDIGApplication.init(UDIGApplication.java:168)
        at org.locationtech.udig.internal.ui.UDIGApplication.start(UDIGApplication.java:126)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.IllegalArgumentException: org.geotools.styling.StyleFactory is not an ImageIO SPI class
        at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
        at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)
        at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155)
        at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:91)
        at org.geotools.factory.CommonFactoryFinder.getServiceRegistry(CommonFactoryFinder.java:76)
        at org.geotools.factory.CommonFactoryFinder.lookup(CommonFactoryFinder.java:346)
        at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:300)
        at org.geotools.factory.CommonFactoryFinder.getFilterFactory2(CommonFactoryFinder.java:390)
        at org.geotools.factory.CommonFactoryFinder.getFilterFactory2(CommonFactoryFinder.java:404)
        at org.geotools.data.DataUtilities.<clinit>(DataUtilities.java:204)
        ... 16 more
```

**Comment by jconley** [comment]
tested with java10, same error
tested with java8 and it works

the website [download page](http://udig.refractions.net/download/) says "Requirements : Java Runtime Environment 1.8++"

perhaps the "++" should be removed unless you expected it to run with java 10 and 11?

**Comment by fgdrf** [comment]
This October is codesprint to upgrade GeoTools & JTS for Java 10 : https://wiki.osgeo.org/wiki/Java_2018_Code_Sprint

I guess its a good point to remove "++" for now, I'll address it

**Comment by fgdrf** [comment]
Please consult Eclipse-Wiki for config.ini file where you can configure which jvm should be used to start uDig : https://wiki.eclipse.org/Eclipse.ini#Specifying_the_JVM

HTH

**Comment by fgdrf** [comment]
Good news: Release Candidate 2.2.0.RC1 has Java 11 Support, please give it a try and please report any issues if you find some ;)

**Comment by Philos-utf8** [comment]
very unbelievable, i can see this page without vpn
