### ISSUE TITLE
ArrayIndexOutOfBoundsException running org.locationtech.udig.catalog.ui.tests on Travis

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#395]
!ENTRY org.eclipse.ui.workbench 4 2 2020-07-03 22:32:39.163
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.locationtech.udig.tools.merge.MergeStartup.earlyStartup(MergeStartup.java:57)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:80)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:56)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.ui 4 0 2020-07-03 22:32:39.169
!MESSAGE Unable to execute early startup code for the org.eclipse.ui.IStartup extension contributed by the 'org.locationtech.udig.tools' plug-in.
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.locationtech.udig.tools.merge.MergeStartup.earlyStartup(MergeStartup.java:57)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:80)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:56)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Warning: NLS unused message: cancel_tooltip in: org.locationtech.udig.ui.internal.messages

**Comment by fgdrf** [comment]
fixed with commit https://github.com/locationtech/udig-platform/commit/85d7690bfd92021018761932338c31f57288242b
