### ISSUE TITLE
NullPointerException in mapEditor while selection in layers view changes

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#406]
!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-08-17 09:48:47.741
!MESSAGE An exception occurred while notifying part listeners
!STACK 0
java.lang.NullPointerException
	at org.locationtech.udig.project.ui.internal.MapEditor$11.callback(MapEditor.java:979)
	at org.locationtech.udig.project.ui.internal.LayerSelectionListener.selectionChanged(LayerSelectionListener.java:55)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:240)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:176)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:217)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:253)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

**Comment by fgdrf** [comment]
see also issue #404 (duplicated code should be extracted to internal class)
