### ISSUE TITLE
OSM Spatial Toolbox with JGrassTools 0.7.3 are incompatible

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#517]
loading `jgt-hortonmachine-0.7.3.jar` and `jgt-jgrassgears-0.7.3.jar` with spatial toolbox (see https://udig.github.io/docs/user/getting_started/Introduction%20to%20the%20Spatial%20Toolbox.html) doesn't work anymore. Its due to incompatibility of jts used in udig (com.locationtech.jts) to the required older version (com.vibidsolution.jts)

```
java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/Geometry
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at oms3.util.Components.getComponentClasses(Components.java:360)
	at org.locationtech.udig.omsbox.core.OmsModulesManager.scanForModules(OmsModulesManager.java:281)
	at org.locationtech.udig.omsbox.core.OmsModulesManager.browseModules(OmsModulesManager.java:169)
	at org.locationtech.udig.omsbox.view.OmsBoxView$8.run(OmsBoxView.java:365)
	at org.locationtech.udig.ui.PlatformGIS$1$2$1.run(PlatformGIS.java:373)
	at org.locationtech.udig.ui.PlatformGIS.lambda$2(PlatformGIS.java:105)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vividsolutions.jts.geom.Geometry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

@moovida is there a newer version available which migrated to the newer org.locationtech.jts packages? Otherwise it looks like we should retire osmbox-module in uDig

**Comment by moovida** [comment]
Hi @fgdrf , the jgrasstools project changed namespace along the way. Therefore, while it is very in line with the latest jts and geotools, it might not be trivial to upgrade it. As sad as I am in saying it, it makes sense to retire the module, since it is not being maintained. Thanks

**Comment by fgdrf** [comment]
@moovida Agree, to sad but fair point if the effort to upgrade to geotools/jts compatible version is to much. What do you think to move it into new community repository in https://github.com/udig organization?

It was a great module and contribution. I love the way how to enhance uDig while by providing addional jars at runtime! However, fare well modul for hydrological analysis :wave:
