### ISSUE TITLE
properties layer & wms layer IllegalArgumentException while trying to add WMS-Layer

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#563]
```
!ENTRY org.locationtech.udig.catalog.ui 4 0 2021-10-13 15:02:05.253
!MESSAGE Error fetching the Title for the resource
!STACK 0
java.lang.IllegalArgumentException: ImageRegistry key already in use: obj16/grid_obj.gif
	at org.eclipse.jface.resource.ImageRegistry.put(ImageRegistry.java:248)
	at org.locationtech.udig.core.AbstractUdigUIPlugin.registerImage(AbstractUdigUIPlugin.java:65)
	at org.locationtech.udig.core.AbstractUdigUIPlugin.getImageDescriptor(AbstractUdigUIPlugin.java:45)
	at org.locationtech.udig.catalog.internal.wms.WMSGeoResourceImpl$WMSResourceInfo.<init>(WMSGeoResourceImpl.java:558)
	at org.locationtech.udig.catalog.internal.wms.WMSGeoResourceImpl.createInfo(WMSGeoResourceImpl.java:152)
	at org.locationtech.udig.catalog.internal.wms.WMSGeoResourceImpl.createInfo(WMSGeoResourceImpl.java:1)
	at org.locationtech.udig.catalog.IGeoResource.getInfo(IGeoResource.java:220)
	at org.locationtech.udig.catalog.internal.wms.WMSGeoResourceImpl.getInfo(WMSGeoResourceImpl.java:140)
	at org.locationtech.udig.catalog.internal.wms.WMSGeoResourceImpl.getInfo(WMSGeoResourceImpl.java:1)
	at org.locationtech.udig.catalog.ui.ResolveTitlesDecorator$UpdateLabel.run(ResolveTitlesDecorator.java:397)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by sschulz92** [comment]
Can you describe what you actually did to get this stacktrace? The title is a hint only (for me).

**Comment by fgdrf** [comment]
> 
> 
> Can you describe what you actually did to get this stacktrace? The title is a hint only (for me).

Updated issue details ;) So you have some data-sets you can test with
